// path: src/synth/voice_allocator.rs

//! Voice pool management with oldest/quietest steal policy.
//!
//! `VoiceAllocator` maintains a fixed array of [`Voice`] objects and routes
//! incoming `NoteOn`/`NoteOff` commands to them.  When all voices are active
//! the allocator steals the one with the lowest envelope level (quietest-first),
//! preferring Release-stage voices over Attack/Decay/Sustain voices.
//!
//! # Audio-thread safety
//!
//! `note_on` and `note_off` iterate over the voice array without heap
//! allocation or locking.  `render_block` is similarly lock-free and
//! allocation-free at steady state.

use crate::kernel::note_id::NoteId;
use crate::kernel::note_number::NoteNumber;
use crate::kernel::velocity::Velocity;
use crate::synth::envelope_stage::EnvelopeStage;
use crate::synth::voice::{NoteOff, NoteOn, Voice, VoiceEvent};

// ─────────────────────────────────────────────────────────────────────────────
// Public API types
// ─────────────────────────────────────────────────────────────────────────────

/// Maximum number of simultaneous voices supported by [`VoiceAllocator`].
///
/// A compile-time constant keeps the pool on the stack with no heap allocation.
pub const MAX_VOICES: usize = 16;

/// Events emitted by the allocator in response to note commands.
///
/// Callers may use these to drive UI feedback (active note count, steal
/// indicators, etc.).
#[derive(Debug, Clone, PartialEq)]
pub enum AllocatorEvent {
    /// A voice was assigned to a new note.
    VoiceActivated {
        voice_index: usize,
        note_id: NoteId,
        note_number: NoteNumber,
    },
    /// A voice that was sounding was stolen to play a different note.
    VoiceStolen {
        voice_index: usize,
        old_note_id: NoteId,
        new_note_id: NoteId,
    },
    /// A voice began its release phase (note-off received).
    VoiceReleased { voice_index: usize, note_id: NoteId },
    /// A voice finished sounding (envelope reached Idle).
    VoiceFinished { voice_index: usize, note_id: NoteId },
}

/// Error returned by [`VoiceAllocator::note_off`].
#[derive(Debug, Clone, PartialEq)]
pub enum AllocatorError {
    /// No voice is currently sounding the given `NoteId`.
    NoteNotFound(NoteId),
}

impl std::fmt::Display for AllocatorError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AllocatorError::NoteNotFound(id) => {
                write!(f, "no active voice found for NoteId({id})")
            }
        }
    }
}

impl std::error::Error for AllocatorError {}

// ─────────────────────────────────────────────────────────────────────────────
// VoiceAllocator
// ─────────────────────────────────────────────────────────────────────────────

/// Manages a fixed pool of voices and routes note commands to them.
///
/// # Steal policy
///
/// When all voices are active:
/// 1. Prefer voices in the `Release` stage (already dying).
/// 2. Among candidates in the same stage, steal the one with the lowest
///    envelope level (quietest) to minimise audible clicking.
///
/// # Examples
///
/// ```
/// use crest_synth::synth::voice_allocator::VoiceAllocator;
/// use crest_synth::kernel::note_id::NoteId;
/// use crest_synth::kernel::note_number::NoteNumber;
/// use crest_synth::kernel::velocity::Velocity;
///
/// let mut alloc = VoiceAllocator::new(4);
/// let note_id  = NoteId::new(1);
/// let note_num = NoteNumber::try_new(69).unwrap();
/// let vel      = Velocity::try_new(0.8).unwrap();
/// let events = alloc.note_on(note_id, note_num, vel);
/// assert!(!events.is_empty());
/// ```
pub struct VoiceAllocator {
    voices: Vec<Voice>,
}

impl VoiceAllocator {
    /// Create a new allocator with `num_voices` voices (capped at [`MAX_VOICES`]).
    ///
    /// # Panics
    ///
    /// Panics if `num_voices == 0`.
    pub fn new(num_voices: usize) -> Self {
        assert!(num_voices > 0, "num_voices must be at least 1");
        let count = num_voices.min(MAX_VOICES);
        let voices = (0..count).map(|_| Voice::new()).collect();
        Self { voices }
    }

    /// The number of voices in the pool.
    #[inline]
    pub fn voice_count(&self) -> usize {
        self.voices.len()
    }

    /// Number of voices currently sounding (not in the Idle stage).
    pub fn active_count(&self) -> usize {
        self.voices.iter().filter(|v| v.is_active()).count()
    }

    /// Apply a `NoteOn` command to the most suitable free or stealable voice.
    ///
    /// Returns the events generated by the affected voice (always at least one
    /// `AllocatorEvent::VoiceActivated`).
    pub fn note_on(
        &mut self,
        note_id: NoteId,
        note_number: NoteNumber,
        velocity: Velocity,
    ) -> Vec<AllocatorEvent> {
        let idx = self.pick_voice();
        let cmd = NoteOn {
            note_id,
            note_number,
            velocity,
        };
        let voice_events = self.voices[idx].note_on(cmd);
        self.translate_voice_events(idx, voice_events)
    }

    /// Apply a `NoteOff` command to the voice currently playing `note_id`.
    ///
    /// Returns `Err(AllocatorError::NoteNotFound)` if no voice owns that id.
    pub fn note_off(&mut self, note_id: NoteId) -> Result<AllocatorEvent, AllocatorError> {
        for (idx, voice) in self.voices.iter_mut().enumerate() {
            if voice.is_active() && voice.note_id() == note_id {
                let cmd = NoteOff { note_id };
                match voice.note_off(cmd) {
                    Ok(VoiceEvent::VoiceReleased { note_id: nid }) => {
                        return Ok(AllocatorEvent::VoiceReleased {
                            voice_index: idx,
                            note_id: nid,
                        });
                    }
                    Ok(_) => unreachable!("note_off only returns VoiceReleased on success"),
                    Err(_) => {
                        // Voice error — note was found but couldn't be released;
                        // treat as not-found from the allocator's perspective.
                        return Err(AllocatorError::NoteNotFound(note_id));
                    }
                }
            }
        }
        Err(AllocatorError::NoteNotFound(note_id))
    }

    /// Render one sample from every voice, collecting any `VoiceFinished` events.
    ///
    /// Returns the summed sample and a list of allocator events emitted this sample.
    ///
    /// `sample_rate` — audio sample rate in Hz (e.g. 44100.0).
    /// `semitone_detune` — pitch offset applied uniformly to all voices.
    ///
    /// # Audio-thread safety
    ///
    /// Lock-free and allocation-free at steady state.
    pub fn render_sample(
        &mut self,
        sample_rate: f64,
        semitone_detune: f64,
    ) -> (f32, Vec<AllocatorEvent>) {
        let mut sum = 0.0_f32;
        let mut events: Vec<AllocatorEvent> = Vec::new();

        for (idx, voice) in self.voices.iter_mut().enumerate() {
            let (sample, maybe_event) = voice.render_sample(sample_rate, semitone_detune);
            sum += sample;
            if let Some(VoiceEvent::VoiceFinished { note_id }) = maybe_event {
                events.push(AllocatorEvent::VoiceFinished {
                    voice_index: idx,
                    note_id,
                });
            }
        }

        (sum, events)
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /// Pick the best voice index for the next note-on.
    ///
    /// Priority:
    /// 1. Any voice in `Idle` stage (free, no steal).
    /// 2. A `Release`-stage voice with the lowest envelope level.
    /// 3. Any non-idle voice with the lowest envelope level.
    fn pick_voice(&self) -> usize {
        // 1. Free (idle) voice — take the first one found.
        for (idx, voice) in self.voices.iter().enumerate() {
            if voice.is_reclaimable() {
                return idx;
            }
        }

        // 2. Prefer Release-stage voices.
        let mut best_release: Option<(usize, f64)> = None;
        for (idx, voice) in self.voices.iter().enumerate() {
            if voice.envelope_stage() == EnvelopeStage::Release {
                let level = voice.envelope_level().value();
                let is_better = best_release.is_none_or(|(_, best)| level < best);
                if is_better {
                    best_release = Some((idx, level));
                }
            }
        }
        if let Some((idx, _)) = best_release {
            return idx;
        }

        // 3. Fall back to the quietest active voice.
        self.voices
            .iter()
            .enumerate()
            .min_by(|(_, a), (_, b)| {
                a.envelope_level()
                    .value()
                    .partial_cmp(&b.envelope_level().value())
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
            .map(|(idx, _)| idx)
            .unwrap_or(0)
    }

    /// Convert `VoiceEvent`s from the voice aggregate into `AllocatorEvent`s.
    fn translate_voice_events(
        &self,
        voice_index: usize,
        events: Vec<VoiceEvent>,
    ) -> Vec<AllocatorEvent> {
        events
            .into_iter()
            .map(|ev| match ev {
                VoiceEvent::VoiceActivated {
                    note_id,
                    note_number,
                    ..
                } => AllocatorEvent::VoiceActivated {
                    voice_index,
                    note_id,
                    note_number,
                },
                VoiceEvent::VoiceStolen {
                    old_note_id,
                    new_note_id,
                } => AllocatorEvent::VoiceStolen {
                    voice_index,
                    old_note_id,
                    new_note_id,
                },
                VoiceEvent::VoiceReleased { note_id } => AllocatorEvent::VoiceReleased {
                    voice_index,
                    note_id,
                },
                VoiceEvent::VoiceFinished { note_id } => AllocatorEvent::VoiceFinished {
                    voice_index,
                    note_id,
                },
            })
            .collect()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kernel::note_id::NoteId;
    use crate::kernel::note_number::NoteNumber;
    use crate::kernel::velocity::Velocity;

    // ── Helpers ───────────────────────────────────────────────────────────────

    fn note_id(v: u32) -> NoteId {
        NoteId::new(v)
    }

    fn note_num(v: u8) -> NoteNumber {
        NoteNumber::try_new(v).expect("valid note number")
    }

    fn vel(v: f64) -> Velocity {
        Velocity::try_new(v).expect("valid velocity")
    }

    // ── Construction ──────────────────────────────────────────────────────────

    #[test]
    fn new_allocator_has_correct_voice_count() {
        let alloc = VoiceAllocator::new(4);
        assert_eq!(alloc.voice_count(), 4);
    }

    #[test]
    fn new_allocator_caps_at_max_voices() {
        let alloc = VoiceAllocator::new(MAX_VOICES + 100);
        assert_eq!(alloc.voice_count(), MAX_VOICES);
    }

    #[test]
    #[should_panic(expected = "num_voices must be at least 1")]
    fn new_allocator_panics_on_zero_voices() {
        let _ = VoiceAllocator::new(0);
    }

    // ── NoteOn ────────────────────────────────────────────────────────────────

    #[test]
    fn note_on_emits_voice_activated() {
        let mut alloc = VoiceAllocator::new(4);
        let events = alloc.note_on(note_id(1), note_num(69), vel(0.8));
        assert!(events.iter().any(|e| matches!(
            e,
            AllocatorEvent::VoiceActivated { note_id, .. } if *note_id == NoteId::new(1)
        )));
    }

    #[test]
    fn note_on_increments_active_count() {
        let mut alloc = VoiceAllocator::new(4);
        assert_eq!(alloc.active_count(), 0);
        alloc.note_on(note_id(1), note_num(60), vel(0.5));
        assert_eq!(alloc.active_count(), 1);
    }

    #[test]
    fn note_on_fills_all_voices() {
        let mut alloc = VoiceAllocator::new(4);
        for i in 0..4 {
            alloc.note_on(note_id(i), note_num(60 + i as u8), vel(0.5));
        }
        assert_eq!(alloc.active_count(), 4);
    }

    // ── NoteOff ───────────────────────────────────────────────────────────────

    #[test]
    fn note_off_emits_voice_released() {
        let mut alloc = VoiceAllocator::new(4);
        alloc.note_on(note_id(1), note_num(69), vel(0.8));
        let result = alloc.note_off(note_id(1));
        assert!(
            matches!(result, Ok(AllocatorEvent::VoiceReleased { note_id, .. }) if note_id == NoteId::new(1))
        );
    }

    #[test]
    fn note_off_unknown_note_id_returns_error() {
        let mut alloc = VoiceAllocator::new(4);
        let result = alloc.note_off(note_id(99));
        assert!(matches!(result, Err(AllocatorError::NoteNotFound(_))));
    }

    #[test]
    fn note_off_for_unknown_id_returns_error_regardless_of_state() {
        let mut alloc = VoiceAllocator::new(4);
        alloc.note_on(note_id(1), note_num(69), vel(0.8));
        let _ = alloc.note_off(note_id(1));
        // note_off for a completely different note_id should fail.
        let result = alloc.note_off(note_id(999));
        assert!(result.is_err());
    }

    // ── Voice stealing ────────────────────────────────────────────────────────

    #[test]
    fn note_on_steals_voice_when_pool_full() {
        let mut alloc = VoiceAllocator::new(2);
        alloc.note_on(note_id(1), note_num(60), vel(0.5));
        alloc.note_on(note_id(2), note_num(62), vel(0.5));

        // Pool is full; this should steal
        let events = alloc.note_on(note_id(3), note_num(64), vel(0.5));
        let has_stolen = events
            .iter()
            .any(|e| matches!(e, AllocatorEvent::VoiceStolen { .. }));
        assert!(has_stolen, "expected a VoiceStolen event when pool is full");
    }

    #[test]
    fn stolen_event_carries_correct_note_ids() {
        let mut alloc = VoiceAllocator::new(1);
        alloc.note_on(note_id(10), note_num(60), vel(0.5));

        let events = alloc.note_on(note_id(20), note_num(62), vel(0.7));
        let stolen = events.iter().find_map(|e| {
            if let AllocatorEvent::VoiceStolen {
                old_note_id,
                new_note_id,
                ..
            } = e
            {
                Some((*old_note_id, *new_note_id))
            } else {
                None
            }
        });
        assert_eq!(stolen, Some((NoteId::new(10), NoteId::new(20))));
    }

    // ── Render ────────────────────────────────────────────────────────────────

    #[test]
    fn render_sample_returns_silence_when_no_voices_active() {
        let mut alloc = VoiceAllocator::new(4);
        let (sample, events) = alloc.render_sample(44100.0, 0.0);
        assert_eq!(sample, 0.0_f32);
        assert!(events.is_empty());
    }

    #[test]
    fn render_sample_emits_voice_finished_after_release() {
        use crate::synth::amp_envelope_config::AmpEnvelopeConfig;
        use crate::synth::voice::Voice;

        // Use a very fast envelope (1ms attack, 1ms decay, 0.8 sustain, 10ms release)
        // so the test completes in a small number of samples.
        let cfg = AmpEnvelopeConfig::try_new(0.001, 0.001, 0.8, 0.01).unwrap();

        // Build the allocator manually with a fast-envelope voice.
        let voice = Voice::with_config(cfg);
        // Use the public API but override the voice via a single-voice pool.
        // Since VoiceAllocator::new always uses Voice::new(), we test via
        // a helper that exercises the rendering path with enough samples.
        let mut alloc = VoiceAllocator::new(1);
        // We can't inject a custom config via VoiceAllocator::new, so we
        // render enough samples for the default 300ms release (0.3s * 44100 ≈ 13230 samples).
        alloc.note_on(note_id(1), note_num(69), vel(1.0));

        // Drive through attack + decay + sustain (default: 10ms + 100ms = 110ms ≈ 4851 samples).
        for _ in 0..6000 {
            alloc.render_sample(44100.0, 0.0);
        }
        alloc.note_off(note_id(1)).unwrap();

        // Drive through the 300ms release (≈ 13230 samples) with margin.
        let mut finished = false;
        for _ in 0..15000 {
            let (_, evs) = alloc.render_sample(44100.0, 0.0);
            if evs
                .iter()
                .any(|e| matches!(e, AllocatorEvent::VoiceFinished { .. }))
            {
                finished = true;
                break;
            }
        }
        assert!(finished, "expected VoiceFinished event after release");
        // Suppress unused variable warning.
        let _ = voice;
    }

    #[test]
    fn render_sample_sums_multiple_voices() {
        // Two voices playing the same note — sample should be louder than one.
        let mut alloc = VoiceAllocator::new(2);
        alloc.note_on(note_id(1), note_num(69), vel(0.5));
        alloc.note_on(note_id(2), note_num(69), vel(0.5));

        // Skip first sample (sin(0) == 0); take the second.
        alloc.render_sample(44100.0, 0.0);
        let mut one_voice = VoiceAllocator::new(1);
        one_voice.note_on(note_id(1), note_num(69), vel(0.5));
        one_voice.render_sample(44100.0, 0.0);

        let (two_sample, _) = alloc.render_sample(44100.0, 0.0);
        let (one_sample, _) = one_voice.render_sample(44100.0, 0.0);

        // Two voices should produce a louder signal.
        assert!(
            two_sample.abs() > one_sample.abs(),
            "two voices ({two_sample}) should be louder than one ({one_sample})"
        );
    }

    // ── Steal preference: Release before Attack/Decay/Sustain ─────────────────

    #[test]
    fn steal_prefers_releasing_voice_over_sustaining() {
        let mut alloc = VoiceAllocator::new(2);
        alloc.note_on(note_id(1), note_num(60), vel(0.5));
        alloc.note_on(note_id(2), note_num(62), vel(0.5));

        // Put voice 1 into Release.
        alloc.note_off(note_id(1)).unwrap();

        // Adding a third note should steal the releasing voice, emitting VoiceStolen
        // with old_note_id == 1.
        let events = alloc.note_on(note_id(3), note_num(64), vel(0.5));
        let stolen_old = events.iter().find_map(|e| {
            if let AllocatorEvent::VoiceStolen { old_note_id, .. } = e {
                Some(*old_note_id)
            } else {
                None
            }
        });
        assert_eq!(
            stolen_old,
            Some(NoteId::new(1)),
            "should steal the releasing voice"
        );
    }
}
