//! Generation of `webview-page/tokens.css` from the authored vocabulary.
//!
//! The webview projection page paints only with CSS custom properties, and
//! every one of those properties is emitted here from the single authored
//! source: the semantic visual vocabulary in [`crate::shell::tokens`]
//! and the responsive bounds in [`crate::shell::density`].
//! No raw value is typed in this module — each declaration reads the same
//! `resolve()`/`metrics()`/accessor the native shell reads, so an authored
//! change lands in the page by regeneration, never by hand-copying. The page
//! declares no raw value the vocabulary already names; a hand-copied or
//! drifted value is a defect.
//!
//! # Name transformation
//!
//! Property names are derived mechanically from the canonical authored names,
//! never assigned per token:
//!
//! - slash-separated canonical names lowercase and swap `/` for `-`
//!   (`color/bg/canvas` → `--color-bg-canvas`, `space/4` → `--space-4`);
//! - type styles expand to four properties per style
//!   (`Display/Screen` → `--type-display-screen-size/-line/-weight/-tracking`);
//! - radii, which the vocabulary names only by variant, kebab their variant
//!   name under a `--radius-` prefix (`Radius::Small` → `--radius-small`);
//! - geometry constants kebab their Rust identifier, dropping the `_PX`
//!   suffix because the unit moves into the value
//!   (`KEYLINE_RESTING_PX` → `--keyline-resting: 1px`);
//! - responsive shell dimensions expand into minimum, preferred, and maximum
//!   properties, while structural media rules are generated from the same
//!   Rust thresholds.
//!
//! The transformation is injective over the declared vocabulary — asserted by
//! test, so a future name collision fails here instead of silently merging
//! two tokens.
//!
//! # Regeneration and freshness
//!
//! `make webview-tokens` regenerates the committed file (it runs the
//! `#[ignore]`d `write_tokens_css` test in this module and nothing else).
//! [`committed_tokens_are_fresh`] is the freshness contract: WP06's
//! acceptance test (T023) reads the committed `webview-page/tokens.css` and
//! calls it; the byte-for-byte comparison and this exact signature are the
//! contract, and weakening the comparison to parsed values is a defect.

use core::fmt;

use crate::shell::density::{ResponsiveShellContract, COMPACT_MAX_WIDTH_PX, STANDARD_MAX_WIDTH_PX};
use crate::shell::tokens::{
    ALL_COLORS, ALL_RADII, ALL_SPACING_STEPS, ALL_TYPE_STYLES, FADER_CAP_HEIGHT_PX,
    FADER_CAP_WIDTH_PX, FADER_FILL_WIDTH_PX, FADER_ROUNDING_PX, FADER_SHOULDER_PX,
    FADER_TRACK_WIDTH_PX, FOCUS_HALO_OPACITY, FOCUS_HALO_RADIUS_PX, FOCUS_HALO_SPREAD_PX,
    KEYLINE_EMPHASIS_PX, KEYLINE_RESTING_PX, MIN_INTERACTIVE_TARGET_PX,
};

/// Renders the complete generated stylesheet: a header naming this generator
/// and one `:root` block holding every custom property the vocabulary
/// declares, in the vocabulary's own declaration order.
///
/// The output is deterministic — same vocabulary, same bytes — which is what
/// makes the committed file's byte-identity a meaningful freshness proof.
pub fn tokens_css() -> String {
    let mut css = String::new();
    css.push_str("/* GENERATED — DO NOT EDIT.\n");
    css.push_str(" * Generated by src/shell/webview/token_export.rs::tokens_css from the\n");
    css.push_str(" * authored vocabulary (src/shell/tokens.rs) and responsive bounds\n");
    css.push_str(" * (src/shell/density.rs). Regenerate with `make webview-tokens`.\n");
    css.push_str(" */\n");
    css.push_str(":root {\n");
    for (property, value) in declarations() {
        css.push_str("  ");
        css.push_str(&property);
        css.push_str(": ");
        css.push_str(&value);
        css.push_str(";\n");
    }
    css.push_str("}\n");
    css.push_str(&format!(
        "@media (max-width: {}) {{\n  :root {{\n    --layout-mode: \"standard\";\n  }}\n}}\n",
        css_px(STANDARD_MAX_WIDTH_PX)
    ));
    css.push_str(&format!(
        "@media (max-width: {}) {{\n  :root {{\n    --layout-mode: \"compact\";\n    --workspace-columns: minmax(0, 1fr);\n    --workspace-rows: minmax(20rem, auto) minmax(20rem, auto);\n    --workspace-areas: \"workspace\" \"side\";\n  }}\n}}\n",
        css_px(COMPACT_MAX_WIDTH_PX)
    ));
    css
}

/// The committed stylesheet no longer matches the generated one.
///
/// Carries the first differing custom property so the failure names the token
/// that drifted, not just "files differ".
#[derive(Debug, Eq, PartialEq)]
pub struct TokenDrift {
    /// The custom property at the first differing line. When the difference
    /// sits outside any declaration (header, braces, line endings), this
    /// describes that location instead.
    pub property: String,
}

impl fmt::Display for TokenDrift {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "committed tokens.css drifted from the authored vocabulary at {}; \
             regenerate with `make webview-tokens`",
            self.property
        )
    }
}

impl std::error::Error for TokenDrift {}

/// Proves the committed `webview-page/tokens.css` is byte-identical to fresh
/// generator output.
///
/// This is the contract WP06's acceptance test calls against the committed
/// file. The comparison is byte-for-byte deliberately: a parsed-value
/// comparison would forgive reformatting, and a reformatted file is exactly
/// the hand-edit this check exists to catch.
pub fn committed_tokens_are_fresh(committed: &str) -> Result<(), TokenDrift> {
    let fresh = tokens_css();
    if committed.as_bytes() == fresh.as_bytes() {
        return Ok(());
    }
    let committed_lines: Vec<&str> = committed.lines().collect();
    let fresh_lines: Vec<&str> = fresh.lines().collect();
    let line_count = committed_lines.len().max(fresh_lines.len());
    for index in 0..line_count {
        let committed_line = committed_lines.get(index).copied().unwrap_or("");
        let fresh_line = fresh_lines.get(index).copied().unwrap_or("");
        if committed_line != fresh_line {
            let property = property_name(fresh_line)
                .or_else(|| property_name(committed_line))
                .unwrap_or_else(|| format!("line {} (outside any declaration)", index + 1));
            return Err(TokenDrift { property });
        }
    }
    // Every line matches but the bytes do not: the difference is invisible to
    // a line split — line endings or a trailing-newline change.
    Err(TokenDrift {
        property: "line endings or trailing whitespace".to_owned(),
    })
}

/// Every generated `(custom property, value)` pair, in emission order.
fn declarations() -> Vec<(String, String)> {
    let mut properties = Vec::new();
    for color in ALL_COLORS {
        properties.push((
            format!("--{}", kebab_canonical(color.canonical_name())),
            css_hex(color.resolve()),
        ));
    }
    for style in ALL_TYPE_STYLES {
        let name = kebab_canonical(style.canonical_name());
        let metrics = style.metrics();
        properties.push((format!("--type-{name}-size"), css_px(metrics.size_px)));
        properties.push((
            format!("--type-{name}-line"),
            css_px(metrics.line_height_px),
        ));
        properties.push((
            format!("--type-{name}-weight"),
            metrics.weight.numeric().to_string(),
        ));
        properties.push((
            format!("--type-{name}-tracking"),
            css_px(metrics.tracking_px),
        ));
    }
    for step in ALL_SPACING_STEPS {
        properties.push((
            format!("--{}", kebab_canonical(step.canonical_name())),
            css_px(step.resolve()),
        ));
    }
    for radius in ALL_RADII {
        properties.push((
            format!("--radius-{}", kebab_camel(&format!("{radius:?}"))),
            css_px(radius.resolve()),
        ));
    }
    let px_constants: [(&str, f32); 5] = [
        (stringify!(KEYLINE_RESTING_PX), KEYLINE_RESTING_PX),
        (stringify!(KEYLINE_EMPHASIS_PX), KEYLINE_EMPHASIS_PX),
        (
            stringify!(MIN_INTERACTIVE_TARGET_PX),
            MIN_INTERACTIVE_TARGET_PX,
        ),
        (stringify!(FOCUS_HALO_RADIUS_PX), FOCUS_HALO_RADIUS_PX),
        (stringify!(FOCUS_HALO_SPREAD_PX), FOCUS_HALO_SPREAD_PX),
    ];
    for (name, value) in px_constants {
        properties.push((format!("--{}", kebab_constant(name)), css_px(value)));
    }
    properties.push((
        format!("--{}", kebab_constant(stringify!(FOCUS_HALO_OPACITY))),
        css_number(FOCUS_HALO_OPACITY),
    ));
    // The fader specimen geometry (mission webview-shell-cutover WP07 T027):
    // the page's fader anatomy resolves these rather than restating the
    // authored pixels as page literals.
    let fader_constants: [(&str, f32); 6] = [
        (stringify!(FADER_TRACK_WIDTH_PX), FADER_TRACK_WIDTH_PX),
        (stringify!(FADER_FILL_WIDTH_PX), FADER_FILL_WIDTH_PX),
        (stringify!(FADER_SHOULDER_PX), FADER_SHOULDER_PX),
        (stringify!(FADER_CAP_WIDTH_PX), FADER_CAP_WIDTH_PX),
        (stringify!(FADER_CAP_HEIGHT_PX), FADER_CAP_HEIGHT_PX),
        (stringify!(FADER_ROUNDING_PX), FADER_ROUNDING_PX),
    ];
    for (name, value) in fader_constants {
        properties.push((format!("--{}", kebab_constant(name)), css_px(value)));
    }
    let responsive = ResponsiveShellContract::get();
    for (name, bounds) in responsive.all_bounds() {
        let name = name.replace(' ', "-");
        for (suffix, value) in [
            ("min", bounds.minimum_px),
            ("preferred", bounds.preferred_px),
            ("max", bounds.maximum_px),
        ] {
            properties.push((format!("--shell-{name}-{suffix}"), css_px(value)));
        }
    }
    properties.push((
        "--shell-utility-bar-thickness".to_owned(),
        css_px(responsive.utility_bar_thickness_px),
    ));
    properties.push((
        "--layout-compact-max-width".to_owned(),
        css_px(COMPACT_MAX_WIDTH_PX),
    ));
    properties.push((
        "--layout-standard-max-width".to_owned(),
        css_px(STANDARD_MAX_WIDTH_PX),
    ));
    properties.push(("--layout-mode".to_owned(), "\"wide\"".to_owned()));
    properties.push(("--shell-text-scale".to_owned(), "1".to_owned()));
    properties.push((
        "--workspace-columns".to_owned(),
        "minmax(0, 1fr) minmax(var(--shell-side-track-min), clamp(var(--shell-side-track-min), 22vw, var(--shell-side-track-max)))".to_owned(),
    ));
    properties.push((
        "--workspace-areas".to_owned(),
        "\"workspace side\"".to_owned(),
    ));
    properties.push(("--workspace-rows".to_owned(), "minmax(0, 1fr)".to_owned()));
    properties.push(("--overview-columns".to_owned(), "minmax(0, 1fr)".to_owned()));
    properties
}

/// Lowercases a slash-separated canonical name and swaps `/` for `-`.
fn kebab_canonical(canonical: &str) -> String {
    canonical.to_lowercase().replace('/', "-")
}

/// Kebab-cases a CamelCase name (`WideReference` → `wide-reference`).
fn kebab_camel(name: &str) -> String {
    let mut kebab = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_ascii_uppercase() && index > 0 {
            kebab.push('-');
        }
        kebab.push(character.to_ascii_lowercase());
    }
    kebab
}

/// Kebab-cases a `SCREAMING_SNAKE` Rust constant identifier, dropping a
/// trailing `_PX` — the unit moves into the emitted value.
fn kebab_constant(name: &str) -> String {
    let kebab = name.to_lowercase().replace('_', "-");
    match kebab.strip_suffix("-px") {
        Some(stripped) => stripped.to_owned(),
        None => kebab,
    }
}

/// Formats an authored number without a trailing `.0` on whole values.
fn css_number(value: f32) -> String {
    if value.fract() == 0.0 {
        format!("{}", value as i64)
    } else {
        format!("{value}")
    }
}

/// Formats an authored pixel value as a CSS length.
fn css_px(value: f32) -> String {
    format!("{}px", css_number(value))
}

/// Formats an authored color as lowercase six-digit hex.
fn css_hex(color: crate::shell::tokens::AuthoredRgb) -> String {
    format!("#{:02x}{:02x}{:02x}", color.r(), color.g(), color.b())
}

/// Extracts the custom property name from a generated declaration line.
fn property_name(line: &str) -> Option<String> {
    let trimmed = line.trim_start();
    if !trimmed.starts_with("--") {
        return None;
    }
    let colon = trimmed.find(':')?;
    Some(trimmed[..colon].to_owned())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shell::tokens::{Radius, SemanticColor, SpacingStep, TypeStyle};
    use std::collections::HashSet;

    fn occurrences(haystack: &str, needle: &str) -> usize {
        haystack.matches(needle).count()
    }

    #[test]
    fn the_stylesheet_opens_with_the_generated_header_and_one_root_block() {
        let css = tokens_css();
        assert!(css.starts_with("/* GENERATED — DO NOT EDIT.\n"));
        assert!(css.contains("src/shell/webview/token_export.rs"));
        assert!(css.contains("make webview-tokens"));
        assert_eq!(occurrences(&css, ":root {"), 3);
        assert!(css.contains("--layout-mode: \"standard\""));
        assert!(css.contains("--layout-mode: \"compact\""));
        assert!(css.ends_with("}\n"));
    }

    /// Every vocabulary member appears exactly once (type styles as exactly
    /// one declaration per expanded metric).
    #[test]
    fn every_vocabulary_member_appears_exactly_once() {
        let css = tokens_css();
        for color in ALL_COLORS {
            let needle = format!("  --{}: ", kebab_canonical(color.canonical_name()));
            assert_eq!(occurrences(&css, &needle), 1, "{}", color.canonical_name());
        }
        for style in ALL_TYPE_STYLES {
            let name = kebab_canonical(style.canonical_name());
            for metric in ["size", "line", "weight", "tracking"] {
                let needle = format!("  --type-{name}-{metric}: ");
                assert_eq!(
                    occurrences(&css, &needle),
                    1,
                    "{} {metric}",
                    style.canonical_name()
                );
            }
        }
        for step in ALL_SPACING_STEPS {
            let needle = format!("  --{}: ", kebab_canonical(step.canonical_name()));
            assert_eq!(occurrences(&css, &needle), 1, "{}", step.canonical_name());
        }
        for radius in ALL_RADII {
            let needle = format!("  --radius-{}: ", kebab_camel(&format!("{radius:?}")));
            assert_eq!(occurrences(&css, &needle), 1, "{radius:?}");
        }
        for constant in [
            "--keyline-resting: ",
            "--keyline-emphasis: ",
            "--min-interactive-target: ",
            "--focus-halo-radius: ",
            "--focus-halo-spread: ",
            "--focus-halo-opacity: ",
            "--fader-track-width: ",
            "--fader-fill-width: ",
            "--fader-shoulder: ",
            "--fader-cap-width: ",
            "--fader-cap-height: ",
            "--fader-rounding: ",
        ] {
            assert_eq!(occurrences(&css, constant), 1, "{constant}");
        }
        for (name, _) in ResponsiveShellContract::get().all_bounds() {
            let name = name.replace(' ', "-");
            for suffix in ["min", "preferred", "max"] {
                let needle = format!("  --shell-{name}-{suffix}: ");
                assert_eq!(occurrences(&css, &needle), 1, "{name} {suffix}");
            }
        }
    }

    /// The name transformation stays injective over the declared vocabulary:
    /// no two authored tokens may collapse onto one custom property.
    #[test]
    fn the_name_transformation_is_injective_over_the_declared_vocabulary() {
        let declarations = declarations();
        let unique: HashSet<&str> = declarations
            .iter()
            .map(|(property, _)| property.as_str())
            .collect();
        assert_eq!(
            unique.len(),
            declarations.len(),
            "two authored tokens share a custom property name"
        );
    }

    /// Spot checks spell the expected declaration text literally, so the
    /// transform and the value format are pinned against the authored
    /// constants rather than against the generator's own helpers. Colors are
    /// the one exception: the repository literal guard
    /// (`tests/component_vocabulary.rs`) forbids spelling an authored hex
    /// outside the vocabulary file, so their expected text is formatted here
    /// in the test from the authored constant's resolved channels.
    #[test]
    fn spot_checked_declarations_match_their_authored_values() {
        let css = tokens_css();
        // The canvas background, formatted from the authored channels rather
        // than through the generator's own hex helper.
        let canvas = SemanticColor::BgCanvas.resolve();
        assert!(css.contains(&format!(
            "  --color-bg-canvas: #{:02x}{:02x}{:02x};\n",
            canvas.r(),
            canvas.g(),
            canvas.b()
        )));
        // color/accent/instrument/plates keeps its full published path.
        let plates = SemanticColor::AccentInstrument.resolve();
        assert!(css.contains(&format!(
            "  --color-accent-instrument-plates: #{:02x}{:02x}{:02x};\n",
            plates.r(),
            plates.g(),
            plates.b()
        )));
        // Display/Screen: 32/40, SemiBold (600), 0.4 px tracking.
        assert!(css.contains("  --type-display-screen-size: 32px;\n"));
        assert!(css.contains("  --type-display-screen-line: 40px;\n"));
        assert!(css.contains("  --type-display-screen-weight: 600;\n"));
        assert!(css.contains("  --type-display-screen-tracking: 0.4px;\n"));
        // space/24 and the small radius.
        assert!(css.contains("  --space-24: 24px;\n"));
        assert!(css.contains("  --radius-small: 4px;\n"));
        assert!(css.contains("  --radius-none: 0px;\n"));
        // Keylines, target, halo.
        assert!(css.contains("  --keyline-resting: 1px;\n"));
        assert!(css.contains("  --keyline-emphasis: 3px;\n"));
        assert!(css.contains("  --min-interactive-target: 48px;\n"));
        assert!(css.contains("  --focus-halo-radius: 8px;\n"));
        assert!(css.contains("  --focus-halo-spread: 1px;\n"));
        assert!(css.contains("  --focus-halo-opacity: 0.28;\n"));
        // The fader specimen geometry, under the exact property names the
        // page's fader anatomy already resolves.
        assert!(css.contains("  --fader-track-width: 14px;\n"));
        assert!(css.contains("  --fader-fill-width: 8px;\n"));
        assert!(css.contains("  --fader-shoulder: 3px;\n"));
        assert!(css.contains("  --fader-cap-width: 34px;\n"));
        assert!(css.contains("  --fader-cap-height: 6px;\n"));
        assert!(css.contains("  --fader-rounding: 2px;\n"));
        assert!(css.contains("  --shell-row-height-min: 48px;\n"));
        assert!(css.contains("  --shell-row-height-preferred: 52px;\n"));
        assert!(css.contains("  --shell-side-track-min: 320px;\n"));
        assert!(css.contains("  --shell-side-track-max: 420px;\n"));
        assert!(css.contains("  --shell-mixer-column-min: 48px;\n"));
        assert!(css.contains("  --layout-compact-max-width: 1023px;\n"));
        assert!(css.contains("  --layout-standard-max-width: 1599px;\n"));
        assert!(css.contains("@media (max-width: 1023px)"));
        assert!(css.contains("@media (max-width: 1599px)"));
    }

    /// Spot checks the values that flow through resolve()/metrics() so a
    /// vocabulary edit regenerates into the page rather than diverging.
    #[test]
    fn generated_values_read_the_authored_accessors() {
        let css = tokens_css();
        assert!(css.contains(&format!(
            "  --color-accent-focus: {};\n",
            css_hex(SemanticColor::AccentFocus.resolve())
        )));
        assert!(css.contains(&format!(
            "  --space-4: {};\n",
            css_px(SpacingStep::S4.resolve())
        )));
        assert!(css.contains(&format!(
            "  --radius-large: {};\n",
            css_px(Radius::Large.resolve())
        )));
        assert!(css.contains(&format!(
            "  --type-code-value-weight: {};\n",
            TypeStyle::CodeValue.metrics().weight.numeric()
        )));
    }

    #[test]
    fn output_is_stable_across_two_calls() {
        assert_eq!(tokens_css(), tokens_css());
    }

    #[test]
    fn fresh_output_passes_the_freshness_check() {
        assert_eq!(committed_tokens_are_fresh(&tokens_css()), Ok(()));
    }

    #[test]
    fn one_mutated_byte_names_the_drifted_property() {
        let mutated = tokens_css().replace("  --space-8: 8px;", "  --space-8: 9px;");
        assert_ne!(mutated, tokens_css(), "the mutation must actually apply");
        let drift = committed_tokens_are_fresh(&mutated)
            .expect_err("a mutated byte must be reported as drift");
        assert_eq!(drift.property, "--space-8");
        assert!(drift.to_string().contains("--space-8"));
        assert!(drift.to_string().contains("make webview-tokens"));
    }

    #[test]
    fn a_deleted_declaration_names_the_missing_property() {
        let truncated = tokens_css().replace("  --keyline-emphasis: 3px;\n", "");
        let drift = committed_tokens_are_fresh(&truncated)
            .expect_err("a deleted declaration must be reported as drift");
        assert_eq!(drift.property, "--keyline-emphasis");
    }

    #[test]
    fn a_mutated_header_byte_is_still_drift() {
        let mutated = tokens_css().replacen("GENERATED", "GENERATeD", 1);
        let drift = committed_tokens_are_fresh(&mutated)
            .expect_err("a header edit must be reported as drift");
        assert_eq!(drift.property, "line 1 (outside any declaration)");
    }

    /// Regenerates the committed stylesheet. Ignored in a normal test run
    /// because it writes into the repository; `make webview-tokens` runs
    /// exactly this test and nothing else.
    #[test]
    #[ignore = "writes webview-page/tokens.css; run via `make webview-tokens`"]
    fn write_tokens_css() {
        let page_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("webview-page");
        std::fs::create_dir_all(&page_dir).expect("webview-page/ must be creatable");
        std::fs::write(page_dir.join("tokens.css"), tokens_css())
            .expect("webview-page/tokens.css must be writable");
    }
}
