#!/usr/bin/env python3
"""Collect the actual notices of the embedded DSP and its native dependencies."""
from pathlib import Path
import gzip, hashlib, json, re, tarfile
ROOT = Path(__file__).resolve().parents[1]
AUDIO = ROOT / 'vendor/audio'
LICENSES = [
    'vendor/braids/stmlib/LICENSE', 'vendor/chorus/LICENSE', 'vendor/rustysynth/LICENSE.txt',
    'airwindows/LICENSE', 'daisysp/LICENSE', 'stk/LICENSE', 'mda/LICENSE', 'mda-deesser/LICENSE.txt',
    'msfa/COPYING', 'stmlib/LICENSE', 'nam/LICENSE', 'nam/Dependencies/AudioDSPTools/LICENSE',
    'nam/Dependencies/nlohmann/LICENSE.MIT', 'nam/Dependencies/eigen/COPYING.MPL2', 'nam/Dependencies/eigen/COPYING.BSD',
    'nam/Dependencies/eigen/COPYING.APACHE', 'nam/Dependencies/eigen/COPYING.MINPACK',
    'fftconvolver/COPYING.txt', 'stretch/LICENSE.txt', 'linear/LICENSE.txt', 'r8brain/LICENSE',
    'sfizz/LICENSE', 'sfizz/src/external/pugixml/LICENSE.md', 'sfizz/src/external/kiss_fft/COPYING',
    'sfizz/src/external/spline/LICENSE', 'sfizz/src/external/hiir/license.txt',
    'sfizz/src/external/cpuid/LICENSE.rst', 'sfizz/src/external/cpuid/platform/LICENSE.rst',
    'sfizz/src/external/tunings/LICENSE.md', 'sfizz/external/atomic_queue/LICENSE',
    'sfizz/external/cephes/LICENSE.txt', 'sfizz/external/filesystem/LICENSE',
    'sfizz/external/invoke.hpp/LICENSE.md', 'sfizz/external/abseil-cpp/LICENSE',
    'sfizz/external/simde/COPYING', 'sfizz/external/st_audiofile/LICENSE.md',
    'sfizz/external/st_audiofile/thirdparty/dr_libs/LICENSE',
    'sfizz/external/st_audiofile/thirdparty/stb_vorbis/LICENSE',
    'sfizz/external/st_audiofile/thirdparty/libaiff/LICENSE',
    'sfizz/external/st_audiofile/thirdparty/wavpack/license.txt',
]
parts = ['Crest Synth — embedded upstream audio notices\n\nGenerated by scripts/audio_notices.py. '
         'The component grants below remain separate; no combined license is asserted. '
         'User-imported models, presets, samples, and IRs are not bundled content.\n\n'
         'Eigen MPL-2.0 source: the corresponding vendored source and its notices are supplied in '
         'EIGEN_SOURCE.tar.gz alongside this file in the application resources.\n\n'
         'Pinned sources:\n' + json.dumps(json.loads((AUDIO/'sources.json').read_text()), indent=2)]
for item in LICENSES:
    path=(ROOT if item.startswith('vendor/') else AUDIO)/item
    parts.append(str(path.relative_to(ROOT))+'\n\n'+path.read_text())
# Mutable grants live in individual DSP files. Faust-generated components retain
# their author/license declarations; their source-library exceptions remain here.
seen=set()
for folder in ['mutable','stmlib','mda','mda-deesser','airwindows','daisysp','stk','msfa','r8brain','sfizz/src/sfizz/effects/gen','sfizz/src/sfizz/gen','sfizz/src/sfizz/dsp','sfizz/src/sfizz/effects/dsp']:
    for path in sorted((AUDIO/folder).rglob('*')):
        if path.suffix not in ('.h','.cc','.cpp','.hxx','.dsp'):continue
        text=path.read_text(errors='strict')
        if path.suffix=='.dsp': prefix=text.split('declare ',1)[0]
        else:
            comments=re.findall(r'/\*.*?\*/|(?m:^//[^\n]*(?:\n//[^\n]*)*)',text[:12000],re.S)
            prefix='\n\n'.join(c for c in comments if re.search(r'copyright|license|permission|exception',c,re.I))
        if prefix and prefix not in seen:
            seen.add(prefix);parts.append(str(path.relative_to(ROOT))+'\n\n'+prefix)
# nlohmann's single-header includes its MIT grant near its end.
json_header=(AUDIO/'nam/Dependencies/nlohmann/json.hpp').read_text()
for comment in re.findall(r'/\*.*?\*/',json_header,re.S):
    if 'Permission is hereby granted' in comment:parts.append('nlohmann JSON and embedded dependency notice\n\n'+comment)
result=ROOT/'assets/licenses/UPSTREAM_AUDIO.txt';result.parent.mkdir(parents=True,exist_ok=True)
result.write_text('\n\n'+'\n\n'.join('='*72+'\n'+part for part in parts)+'\n')
# Hash the actual vendored bytes, including nested dependencies. Builds stage
# adaptations in OUT_DIR; these checksums cover the unchanged input source.
for name, pin in json.loads((AUDIO/'sources.json').read_text()).items():
    folder=AUDIO/pin.get('destination',name)
    if folder.exists():
        records=[f'{hashlib.sha256(path.read_bytes()).hexdigest()}  {path.relative_to(folder)}' for path in sorted(folder.rglob('*')) if path.is_file() and path.name not in ('SHA256SUMS','PROVENANCE.md')]
        (folder/'SHA256SUMS').write_text('\n'.join(records)+'\n')
print(result.relative_to(ROOT),result.stat().st_size)

# Supply the actual MPL-covered source with binary bundles. Normalized archive
# metadata makes the source artifact reproducible without network availability.
eigen = AUDIO / 'nam/Dependencies/eigen'
archive = ROOT / 'assets/licenses/EIGEN_SOURCE.tar.gz'
with archive.open('wb') as output:
    with gzip.GzipFile(fileobj=output, mode='wb', filename='', mtime=0) as compressed:
        with tarfile.open(fileobj=compressed, mode='w') as package:
            for path in sorted(eigen.rglob('*')):
                if not path.is_file():
                    continue
                info = package.gettarinfo(str(path), arcname='eigen/'+str(path.relative_to(eigen)))
                info.uid = info.gid = info.mtime = 0
                info.uname = info.gname = ''
                info.mode = 0o644
                with path.open('rb') as source:
                    package.addfile(info, source)
print(archive.relative_to(ROOT), archive.stat().st_size)
